modbus_tcp_devices:
  - name: PLC1
    ip: "127.0.0.1"
    port: 5502
    timeout: 1
    poll_delay: 1
    tags:
      - name: "PIT-1001"
        value_type: "Real"
        modbus_function: "Holding"
        address: 0
      - name: "PIT-1002"
        value_type: "Real"
        modbus_function: "Holding"
        address: 2
      - name: "TIT-1001"
        value_type: "Real"
        modbus_function: "Holding"
        address: 4
db_path: "../database.db"
